### ISSUE TITLE
SDK usage

### ISSUE THREAD

**Issue by vanbroup** [tencentcloudplatform/tcpicli#29]
In general, the package doesn't really use convenient structs but it can be useful to automatically create or purge some services without having to write a Tencent implementation myself.

Can this package be used as an SDK?

The CLI version of this command below works, using it as below always returns an authentication error:

```go
package main

import (
	"fmt"

	"github.com/tencentcloudplatform/tcpicli/cdn"
	"github.com/tencentcloudplatform/tcpicli/core"
)

func main() {
	fmt.Println("CurrentProfile:", core.CurrentProfile())

	var options string
	options += " host=www.example.com"
	options += " projectId=0"
	options += " hostType=cname"
	options += " origin=1.1.1.1"
	options += " origin=1.1.1.2"
	options += " origin=1.1.1.3"

	b, err := cdn.AddCdnHost(options)
	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Printf("%s (%s)", b.CodeDesc, b.Message)
}
```

```json
CurrentProfile: default
{
  "code": 4100,
  "codeDesc": "AuthFailure",
  "message": "鉴权失败，请参考文档中鉴权部分。"
}
```

**Comment by kiyor** [comment]
Hi, please follow this example:

```
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/tencentcloudplatform/tcpicli/cdn"
	"github.com/tencentcloudplatform/tcpicli/core"
)

func main() {
	fmt.Println("CurrentProfile:", core.CurrentProfile())

	var options []string
	options = append(options, "host=www.example.com")
	options = append(options, "projectId=0")
	options = append(options, "hostType=cname")
	options = append(options, "origin=1.1.1.1")

	client := cdn.NewClient()
//	client.SetLog(os.Stdout, "", log.LstdFlags|log.Lshortfile)
	b, err := client.AddCdnHost(options...)
	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Printf("%s (%s)", b.CodeDesc, b.Message)
}
```

**Comment by vanbroup** [comment]
Thanks, so the arguments must be given as a slice. I did some tests using `cdn.NewClient()` as above but that didn't work eighter. 

Any plans for a more robust [GO style](https://github.com/golang/go/wiki/CodeReviewComments) SDK with a normal request and response struct?

**Comment by kiyor** [comment]
The project initially is not design as SDK, for some reason we decide to make like SDK and more user friendly. If you'd like to have request and response struct, I will suggest my colleague's [repo](https://github.com/zqfan/tencentcloud-sdk-go) and see if it's fit your requirement.
